project:
  type: website

website:
  title: "Anson-Wu"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ANSON202
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



